ns1:
  dxl_unify_handler:
    ros__parameters:
      target_baudrate: 1000000
      device_name: "/dev/ttyUSB2"
      latency_timer: 4
      min_id: 0
      max_id: 45
      min_search_baudrate: 9600
      max_search_baudrate: 2000000